export const TRANSACTION_STATUS = {
    PENDING: 'Pendiente',
    SELLER_APPROVED: 'Aprobada por el vendedor',
    ENDED: 'Finalizada'
}

export const TRANSACTION_STATUS_LIST = [
    TRANSACTION_STATUS.PENDING,
    TRANSACTION_STATUS.SELLER_APPROVED,
    TRANSACTION_STATUS.ENDED
]

export const STATUS_CODES = {
    SERVER_ERROR: 500,
    BAD_REQUEST: 400,
    NOT_FOUND: 404,
    UNIQUE_VIOLATION: 409,
    OK: 200,
    CREATED: 201,
    FORBIDDEN: 403
}

export const OPEN_TYPES = {
    REGISTER: 'REGISTER',
    PURCHASE: 'PURCHASE'
}